In [1]:
from matplotlib import pyplot as plt

print(plt.imread.__doc__)


    Read an image from a file into an array.

    .. note::

        This function exists for historical reasons.  It is recommended to
        use `PIL.Image.open` instead for loading images.

    Parameters
    ----------
    fname : str or file-like
        The image file to read: a filename, a URL or a file-like object opened
        in read-binary mode.

        Passing a URL is deprecated.  Please open the URL
        for reading and pass the result to Pillow, e.g. with
        ``np.array(PIL.Image.open(urllib.request.urlopen(url)))``.
    format : str, optional
        The image file format assumed for reading the data.  The image is
        loaded as a PNG file if *format* is set to "png", if *fname* is a path
        or opened file with a ".png" extension, or if it is an URL.  In all
        other cases, *format* is ignored and the format is auto-detected by
        `PIL.Image.open`.

    Returns
    -------
    `numpy.array`
        The image data. The returned array has sha

In [4]:
im = plt.imread("/home/iqrorjoon/PycharmProjects/all matplotlib functions/base/simple_image.jpg")

print(im)

[[[11 11 11]
  [ 8  8  8]
  [ 6  6  6]
  ...
  [71 74 57]
  [76 79 62]
  [51 54 37]]

 [[ 8  8  8]
  [ 8  8  8]
  [ 9  9  9]
  ...
  [75 78 61]
  [77 80 63]
  [48 51 34]]

 [[ 6  6  6]
  [ 9  9  9]
  [11 11 11]
  ...
  [79 80 64]
  [82 83 67]
  [53 54 38]]

 ...

 [[11 11  9]
  [13 13 11]
  [ 8  8  6]
  ...
  [19 20 15]
  [15 16 11]
  [ 8  9  4]]

 [[ 9  9  7]
  [11 11  9]
  [ 6  6  4]
  ...
  [17 18 13]
  [15 16 11]
  [10 11  6]]

 [[ 8  8  6]
  [10 10  8]
  [ 5  5  3]
  ...
  [19 20 15]
  [18 19 14]
  [14 15 10]]]
